[package]
name = "printpdf"
version = "0.8.0"
authors = [
    "Felix Schütt <felix.schuett@maps4print.com>",
    "Julien Schminke <julien.schminke@web.de",
]
repository = "https://github.com/fschutt/printpdf"
homepage = "https://github.com/fschutt/printpdf"
license = "MIT"
readme = "README.md"
description = "Rust library for reading and writing PDF files"
keywords = ["pdf", "gui", "graphics", "wkhtmltopdf"]
categories = ["gui"]
exclude = ["./assets/*", "./doc/*", "./examples/*"]
autoexamples = false
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lopdf = { git = "https://github.com/J-F-Liu/lopdf", rev = "80a6c505bf8303c74b3057c8e53d4f791e92e126", default-features = false, features = [
    "nom_parser",
] }
time = { version = "0.3.25", default-features = false, features = ["std", "serde", "serde-human-readable"] }
allsorts = { version = "0.15", git = "https://github.com/fschutt/allsorts", branch = "optional-brotli", default-features = false, features = ["flate2_rust"] }
image = { version = "0.25", default-features = false }
svg2pdf = { version = "0.12.0" }
base64 = "0.22.1"
serde = { version = "1" }
serde_derive = { version = "1" }
flate2 = "1.0.35" # for decompression of builtin fonts
# feature=html, independent of feature=wasm
azul-css = { git = "https://github.com/fschutt/azul", rev = "a09ccbd5be6429f8c40c1acd5ebe05850a45380f", default-features = false, optional = true }
azul-css-parser = {  git = "https://github.com/fschutt/azul", rev = "a09ccbd5be6429f8c40c1acd5ebe05850a45380f", default-features = false, optional = true }
azul-core = {  git = "https://github.com/fschutt/azul", rev = "a09ccbd5be6429f8c40c1acd5ebe05850a45380f", default-features = false, features = ["std"], optional = true }
azul-layout = {  git = "https://github.com/fschutt/azul", rev = "a09ccbd5be6429f8c40c1acd5ebe05850a45380f", default-features = false, features = ["std", "text_layout"], optional = true }
azul-text-layout = {  git = "https://github.com/fschutt/azul", rev = "a09ccbd5be6429f8c40c1acd5ebe05850a45380f", default-features = false, optional = true }
azulc = {  git = "https://github.com/fschutt/azul", rev = "a09ccbd5be6429f8c40c1acd5ebe05850a45380f", default-features = false, features = ["std", "xml", "text_layout", "font_loading"], optional = true }
rust-fontconfig = { version = "0.1.13", default-features = false, optional = true }
xmlparser = { version = "0.13.6", default-features = false, optional = true }
serde_json = { version = "1", optional = true }
web-sys = { version = "0.3.77", optional = true, default-features = false, features = ["ImageData", "Window", "Document", "Blob", "CanvasRenderingContext2d", "HtmlCanvasElement", "HtmlImageElement", "ImageBitmap", "BlobPropertyBag"]}
wasm-bindgen-futures = { version = "0.4.50", optional = true, default-features = false }
kuchiki = { version = "0.8.1", optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = { version = "0.2" }
serde_json = { version = "1" }

[features]
default = ["html"]
html = ["kuchiki", "azul-css", "azul-css-parser", "azul-core", "azul-layout", "azul-text-layout", "azulc", "rust-fontconfig", "xmlparser", "serde_json"]
js-sys = ["dep:js-sys", "web-sys", "wasm-bindgen-futures"] # wasm + browser context
gif = ["image/gif"]
jpeg = ["image/jpeg"]
png = ["image/png"]
pnm = ["image/pnm"]
tiff = ["image/tiff"]
bmp = ["image/bmp"]
ico = ["image/ico"]
tga = ["image/tga"]
hdr = ["image/hdr"]
dds = ["image/dds"]
webp = ["image/webp"]
rayon = ["image/rayon"] # enables multithreading for decoding images

[package.metadata.docs.rs]
all-features = true

[target.'cfg(all(target_arch="wasm32",target_os="unknown"))'.dependencies]
js-sys = { version = "0.3.40", optional = true }

[[example]]
name = "simple"
required-features = []

[[example]]
name = "html"
required-features = ["html"]

# re-generates the /defaultfonts/*.ttf fonts
[[example]]
name = "subset"
required-features = []

[[example]]
name = "image"
required-features = ["png"]

[[example]]
name = "render"
required-features = []
