[package]
name = "printpdf"
version = "0.8.0"
authors = [
    "Felix Schütt <felix.schuett@maps4print.com>",
    "Julien Schminke <julien.schminke@web.de",
]
repository = "https://github.com/fschutt/printpdf"
homepage = "https://github.com/fschutt/printpdf"
license = "MIT"
readme = "README.md"
description = "Rust library for reading and writing PDF files"
keywords = ["pdf", "gui", "graphics", "wkhtmltopdf"]
categories = ["gui"]
exclude = ["./assets/*", "./doc/*", "./examples/*"]
autoexamples = false
edition = "2021"

[dependencies]
lopdf = { git = "https://github.com/J-F-Liu/lopdf", rev = "80a6c505bf8303c74b3057c8e53d4f791e92e126", default-features = false, features = [
    "nom_parser",
] }
time = { version = "0.3.25", default-features = false, features = ["std"] }
allsorts = { version = "0.15", git = "https://github.com/fschutt/allsorts", branch = "optional-brotli", default-features = false, features = ["flate2_rust"] }
pdf-writer = { version = "0.12.0" }
image = { version = "0.25", default-features = false }
svg2pdf = { version = "0.12.0" }
# dependencies for wasm demo
azul-css = { git = "https://github.com/fschutt/azul", rev = "a1470af7acda30fbb4416b64a787c038f552d54d", default-features = false }
azul-css-parser = {  git = "https://github.com/fschutt/azul", rev = "a1470af7acda30fbb4416b64a787c038f552d54d", default-features = false }
azul-core = {  git = "https://github.com/fschutt/azul", rev = "a1470af7acda30fbb4416b64a787c038f552d54d", default-features = false, features = ["std"] }
azul-layout = {  git = "https://github.com/fschutt/azul", rev = "a1470af7acda30fbb4416b64a787c038f552d54d", default-features = false, features = ["std", "text_layout"] }
azul-text-layout = {  git = "https://github.com/fschutt/azul", rev = "a1470af7acda30fbb4416b64a787c038f552d54d", default-features = false }
azulc = {  git = "https://github.com/fschutt/azul", rev = "a1470af7acda30fbb4416b64a787c038f552d54d", default-features = false, features = ["std", "xml", "text_layout", "font_loading"] }
rust-fontconfig = { version = "0.1.13", default-features = false }
xmlparser = { version = "0.13.6", default-features = false }
serde = { version = "1" }
serde_derive = { version = "1" }
serde_json = { version = "1" }
wasm-bindgen = { version = "0.2" }
base64 = "0.22.1"
flate2 = "1.0.35"

[profile.release]
lto = true
opt-level = 's'
debug = true

[features]
default = ["js-sys"]
gif = ["image/gif"]
jpeg = ["image/jpeg"]
png = ["image/png"]
pnm = ["image/pnm"]
tiff = ["image/tiff"]
bmp = ["image/bmp"]
ico = ["image/ico"]
tga = ["image/tga"]
hdr = ["image/hdr"]
dds = ["image/dds"]
webp = ["image/webp"]
woff2 = ["allsorts/brotli", "azul-text-layout/woff2"]
rayon = ["image/rayon"] # enables multithreading for decoding images
js-sys = ["dep:js-sys"] # enables js-sys features on wasm

[package.metadata.docs.rs]
all-features = true

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(all(target_arch="wasm32",target_os="unknown"))'.dependencies]
js-sys = { version = "0.3.40", optional = true }

[[example]]
name = "simple"
required-features = []

[[example]]
name = "html"
required-features = []

# re-generates the /defaultfonts/*.ttf fonts
[[example]]
name = "subset"
required-features = []

[[example]]
name = "image"
required-features = ["png"]
