[package]
name = "printpdf"
version = "0.7.0"
authors = [
    "Felix Schütt <felix.schuett@maps4print.com>",
    "Julien Schminke <julien.schminke@web.de",
]
repository = "https://github.com/fschutt/printpdf"
homepage = "https://github.com/fschutt/printpdf"
license = "MIT"
readme = "README.md"
description = "Rust library for reading and writing PDF files"
keywords = ["pdf", "gui", "graphics", "wkhtmltopdf"]
categories = ["gui"]
exclude = ["./assets/*", "./doc/*", "./examples/*"]
autoexamples = false
edition = "2021"

[dependencies]
lopdf = { version = "0.33.0", default-features = false, features = ["pom_parser"] }
time = { version = "0.3.25", default-features = false, features = ["std"] }
allsorts = { version = "0.15", default-features = false, features = ["flate2_rust"] }
xmlparser = { version = "0.13.6", default-features = false }
azul-css = { git = "https://github.com/fschutt/azul", rev = "e306619a820236caf7a01bd7719715fa31f9a8f0", default-features = false }
azul-css-parser = {  git = "https://github.com/fschutt/azul", rev = "e306619a820236caf7a01bd7719715fa31f9a8f0", default-features = false }
azul-core = {  git = "https://github.com/fschutt/azul", rev = "e306619a820236caf7a01bd7719715fa31f9a8f0", default-features = false, features = ["std"] }
azul-layout = {  git = "https://github.com/fschutt/azul", rev = "e306619a820236caf7a01bd7719715fa31f9a8f0", default-features = false, features = ["std", "text_layout"] }
azul-text-layout = {  git = "https://github.com/fschutt/azul", rev = "e306619a820236caf7a01bd7719715fa31f9a8f0", default-features = false }
azulc = {  git = "https://github.com/fschutt/azul", rev = "e306619a820236caf7a01bd7719715fa31f9a8f0", default-features = false, features = ["std", "xml", "text_layout", "font_loading"] }
pdf-writer = { version = "0.9" }
image = { version = "0.25", default-features = false} 
svg2pdf = { version = "0.10" }
rust-fontconfig = { version = "0.1.12", default-features = false }
serde = { version = "1" }
serde_derive = { version = "1" }
serde_json = { version = "1" }
wasm-bindgen = { version = "0.2" }

[features]
default = ["js-sys"]
gif = ["image/gif"]
jpeg = ["image/jpeg"]
png = ["image/png"]
pnm = ["image/pnm"]
tiff = ["image/tiff"]
bmp = ["image/bmp"]
ico = ["image/ico"]
tga = ["image/tga"]
hdr = ["image/hdr"]
dds = ["image/dds"]
webp = ["image/webp"]
rayon = ["image/rayon"]  # enables multithreading for decoding images
js-sys = ["dep:js-sys"] # enables js-sys features on wasm

[package.metadata.docs.rs]
all-features = true

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(all(target_arch="wasm32",target_os="unknown"))'.dependencies]
js-sys = { version = "0.3.40", optional = true }

[[example]]
name = "simple"
required-features = []

[[example]]
name = "html"
required-features = []
