style_edition = "2021"
overflow_delimited_expr = false
reorder_imports = true
indent_style = "Block"
newline_style = "unix"
use_field_init_shorthand = true
use_try_shorthand = true
unstable_features = true
comment_width = 100
error_on_line_overflow = false
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
normalize_doc_attributes = true
wrap_comments = true
imports_granularity = "Crate"