# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wasm-pack build
        run: wasm-pack build --target web --no-pack --no-typescript --release --no-default-features --features "js-sys"
      - name: Generate index.html (release mode)
        run: python3 ./postbuild.py --build-prod
